config:
  target: "http://load-balancer-dns-name"
  phases:
    - duration: 120 
      arrivalRate: 20 
    - duration: 120 
      arrivalRate: 40 
    - duration: 120 
      arrivalRate: 60 
    - duration: 120 
      arrivalRate: 80 
  defaults:
    timeout: 15

scenarios:
  - flow:
      - post:
          url: "/predict"
          json:
            title: "JoJo's Hot Dogs and BBQ"
